apiVersion: v1
kind: Service
metadata:
  name: steps-fe
  labels:
    app: steps-api
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 5000
  selector:
    app: steps-api
    tier: frontend
